---
- name: Configure Homelab Linux System
  hosts: satellite1
  become: true

  vars_files:
    - inventory/vault.yml
  
  tasks:
    - name: General Configuration
      ansible.builtin.include_role:
        name: common
      tags:
        - common

    - name: Deploy Satellite
      ansible.builtin.include_role:
        name: deploy-satellite
      tags:
        - deploy-satellite