---
- name: Configure Homelab Linux System
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: General Configuration
      ansible.builtin.include_role:
        name: common
      tags:
        - common

    - name: Wireguard Server
      ansible.builtin.include_role:
        name: wireguard
      when: ansible_hostname == "wireguard"

    - name: Deploy Netbox on Podman
      ansible.builtin.include_role:
        name: netbox-podman
      when: ansible_hostname == "podman1"