all:
  hosts:
    prddock1:
      ansible_host: 192.168.1.27
      ansible_user: kevin
      ansible_password: "{{ prddock1_become_pass }}"
      ansible_become_password: "{{ prddock1_become_pass }}"
    prdidm1:
      ansible_host: 192.168.1.12
      ansible_user: kevin
      ansible_password: "{{ prdidm1_become_pass }}"
      ansible_become_password: "{{ prdidm1_become_pass }}"
    satellite1:
      ansible_host: 192.168.1.14
      ansible_user: kevin
      ansible_password: "{{ satellite1_become_pass }}"
      ansible_become_password: "{{ satellite1_become_pass }}"
    wireguard:
      ansible_host: 192.168.1.16
      ansible_user: kevin
      ansible_password: "{{ wireguard_become_pass }}"
      ansible_become_password: "{{ wireguard_become_pass }}"
    netbox1:
      ansible_host: 192.168.1.18
      ansible_user: kevin
      ansible_password: "{{ netbox1_become_pass }}"
      ansible_become_password: "{{ netbox1_become_pass }}"
    file1:
      ansible_host: 192.168.1.21
      ansible_user: kevin
      ansible_password: "{{ ovpn_become_pass }}"
      ansible_become_password: "{{ ovpn_become_pass }}"
    ovpn:
      ansible_host: 192.168.1.22
      ansible_user: kevin
      ansible_password: "{{ ovpn_become_pass }}"
      ansible_become_password: "{{ ovpn_become_pass }}"