---
# tasks file for common
- name: Set SELinux Targeted Enforcing
  ansible.posix.selinux:
    policy: targeted
    state: enforcing

- name: Set Hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Configure DNS
  ansible.builtin.template:
      

- name: Set NTP

- name: Join Satellite Server

- name: Attach Subscriptions?

- name: Install Common Packages

- name: Join Domain/IdM Environment

- name: Set Message of the Day (/etc/motd)

- name: Set Pre-Authentication Banner (/etc/banner)

- name: Configure SSHD

- name: Configure Syslog Forwarding

- name: Configure SNMP