---
- name: Install PostgreSQL Package(s)
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - postgresql-server

- name: Initalize PostgreSQL Database
  ansible.builtin.command:
    cmd: postgresql-setup --initdb
  ignore_errors: true

- name: Modify PostgreSQL Client Authentication Configuration File
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/data/pg_hba.conf
  backup: true

- name: Start PostgreSQL Service
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true

- name: Create NetBox Database
  community.postgresql.postgresql_db:
    name: netbox
    state: present

- name: Create NetBox User
  community.postgresql.postgresql_user:
    name: netbox
    password: "{{ postgres_netbox_password }}"

- name: Set NetBox Database Owner
  community.postgresql.postgresql_db:
    name: netbox
    state: present
    owner: netbox